# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: DIANA WANJIRU | PORTFOLIO
email: dee18wanjiru@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
   I'm Diana Wanjiru, a cybersecurity student and aspiring SOC Analyst passionate about cloud security, Linux, and digital defense.
twitter_username: Dee
github_username: wanjirudiana
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:title/
paginate: 0 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "DIANA WANJIRU"
  avatar : "/assets/images/Dee.jpg"
  bio    : "Cybersecurity student | Aspiring SOC Analyst | AWS re/Start Graduate"
  links:
    - label: "GitHub" 
      icon: "fab fa-fw fa-github" 
      url: "https://github.com/wanjirudiana" 
    - label: "LinkedIn" 
      icon: "fab fa-fw fa-linkedin" 
      url: "https://www.linkedin.com/in/diana21wanjiru/" 
    - label: "TryHackMe" 
      icon: "fas fa-fw fa-bug" 
      url: "https://tryhackme.com/p/dee3" 
    - label: "Hack The Box" 
      icon: "fas fa-fw fa-terminal" 
      url: "https://academy.hackthebox.com/dashboard" 
    - label: "Email" 
      icon: "fas fa-fw fa-envelope" 
      url: "mailto:dee18wanjiru@gmail.com"

footer:
  links:
    - label: "GitHub" 
      icon: "fab fa-fw fa-github" 
      url: "https://github.com/wanjirudiana" 
    - label: "LinkedIn" 
      icon: "fab fa-fw fa-linkedin" 
      url: "https://www.linkedin.com/in/diana21wanjiru/"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
